# Checks for patch version updates weekly and minor/major version updates quarterly
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "*/10 * * * *"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "*/5 * * * *"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
